# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: schemas/file/v1/file.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'schemas/file/v1/file.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aschemas/file/v1/file.proto\x12\x07\x66ile.v1\"\xb2\x01\n\x11\x46ileEventEnvelope\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07\x66ile_id\x18\x02 \x01(\t\x12\x10\n\x08\x66ilename\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\x12(\n\nfile_event\x18\n \x01(\x0b\x32\x12.file.v1.FileEventH\x00\x12(\n\x08\x66ile_cmd\x18\x0b \x01(\x0b\x32\x14.file.v1.FileCommandH\x00\x42\x07\n\x05\x65vent\"\x97\x01\n\tFileEvent\x12\x0c\n\x04path\x18\x01 \x01(\t\x12!\n\x05state\x18\x02 \x01(\x0e\x32\x12.file.v1.FileState\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\r\n\x05\x65rror\x18\x04 \x01(\t\x12\x10\n\x08progress\x18\x05 \x01(\t\x12\x12\n\nproject_id\x18\x06 \x01(\t\x12\x13\n\x0bschema_name\x18\x07 \x01(\t\"\xc3\x01\n\x0b\x46ileCommand\x12)\n\x07\x63ommand\x18\x01 \x01(\x0e\x32\x18.file.v1.FileCommandType\x12\x12\n\nproject_id\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12\x14\n\x0c\x63ompany_name\x18\x04 \x01(\t\x12\x14\n\x0cperiod_start\x18\x05 \x01(\t\x12\x12\n\nperiod_end\x18\x06 \x01(\t\x12\x0f\n\x07s3_path\x18\x07 \x01(\t\x12\x13\n\x0bschema_name\x18\x08 \x01(\t*\xef\x01\n\tFileState\x12\x1a\n\x16\x46ILE_STATE_UNSPECIFIED\x10\x00\x12\x16\n\x12\x46ILE_STATE_CREATED\x10\x01\x12\x17\n\x13\x46ILE_STATE_UPLOADED\x10\x02\x12\x18\n\x14\x46ILE_STATE_SCHEDULED\x10\x03\x12\x19\n\x15\x46ILE_STATE_PROCESSING\x10\x04\x12\x18\n\x14\x46ILE_STATE_PROCESSED\x10\x05\x12\x16\n\x12\x46ILE_STATE_DELETED\x10\x06\x12\x14\n\x10\x46ILE_STATE_ERROR\x10\x07\x12\x18\n\x14\x46ILE_STATE_CANCELLED\x10\x08*\xb5\x01\n\x0f\x46ileCommandType\x12\x1c\n\x18\x46ILE_COMMAND_UNSPECIFIED\x10\x00\x12\x18\n\x14\x46ILE_COMMAND_EXTRACT\x10\x01\x12\x1a\n\x16\x46ILE_COMMAND_OVERWRITE\x10\x02\x12\x17\n\x13\x46ILE_COMMAND_DELETE\x10\x03\x12\x17\n\x13\x46ILE_COMMAND_CANCEL\x10\x04\x12\x1c\n\x18\x46ILE_COMMAND_RECALCULATE\x10\x05\x42:Z8github.com/looptroops/socket/internal/pb/schemas/file/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schemas.file.v1.file_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z8github.com/looptroops/socket/internal/pb/schemas/file/v1'
  _globals['_FILESTATE']._serialized_start=573
  _globals['_FILESTATE']._serialized_end=812
  _globals['_FILECOMMANDTYPE']._serialized_start=815
  _globals['_FILECOMMANDTYPE']._serialized_end=996
  _globals['_FILEEVENTENVELOPE']._serialized_start=40
  _globals['_FILEEVENTENVELOPE']._serialized_end=218
  _globals['_FILEEVENT']._serialized_start=221
  _globals['_FILEEVENT']._serialized_end=372
  _globals['_FILECOMMAND']._serialized_start=375
  _globals['_FILECOMMAND']._serialized_end=570
# @@protoc_insertion_point(module_scope)
